name: publish-docker-image

on:
  release:
    types: [published, created]

jobs:
  build-server:
    runs-on: ubuntu-latest
    # permissions:
    #   # Needed to upload contianer images to ghcr.io
    #   packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: prepare variables
        uses: ./.github/actions/docker-push-variables
        id: ev
      - name: Docker Login Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: make empty clients
        run: |
          mkdir -p ./gen-ts-api
          mkdir -p ./gen-go-api
      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name == 'release' }}
          platforms: linux/amd64,linux/arm64
          # build-args: |
          #   VERSION=${{ steps.ev.outputs.version }}
          #   VERSION_FAMILY=${{ steps.ev.outputs.versionFamily }}